version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
      args:
        PUBLIC_PATH: "${FRONTEND_PUBLIC_PATH:-/}"
    ports:
      - "${FRONTEND_PUBLIC_PORT:-80}:80"
    networks:
      - internal
    depends_on:
      - backend
    restart: unless-stopped

  backend-router:
    build:
      context: ./
      dockerfile: ./backend/services/router/Dockerfile
    env_file:
      - backend/services/router/.env
    networks:
      - internal
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  backend-cinema:
    build:
      context: ./
      dockerfile: ./backend/services/cinema/Dockerfile
    env_file:
      - backend/services/cinema/.env
    networks:
      - internal
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    networks:
      - internal
    restart: unless-stopped

  mongo:
    image: "mongo"
    volumes:
      - mongo_data:/data/db
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    driver: bridge

volumes:
  mongo_data:
