version: '3'
services:
  frontend:
    image: docker.pkg.github.com/kotborealis/synch/synch_frontend:latest
    ports:
      - "${FRONTEND_PUBLIC_PORT:-80}:80"
    networks:
      - internal
    depends_on:
      - backend-router
      - backend-cinema
    restart: unless-stopped

  backend-router:
    image: docker.pkg.github.com/kotborealis/synch/synch_backend-router:latest
    env_file:
      - backend/services/router/.env
    networks:
      - internal
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  backend-cinema:
    image: docker.pkg.github.com/kotborealis/synch/synch_backend-router:latest
    env_file:
      - backend/services/cinema/.env
    networks:
      - internal
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    networks:
      - internal
    restart: unless-stopped

  mongo:
    image: "mongo"
    volumes:
      - mongo_data:/data/db
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    driver: bridge

volumes:
  mongo_data:
